Update typescript to 5.1.6
depcheck/depcheck pull request #815
Opened 2023-06-29 19:48 UTC by znarf

May fix https://github.com/depcheck/depcheck/issues/814

2023-07-03 16:07 UTC, vivi90 requested changes
Please change to `^4.9.0` or `^4.9.5` instead.
But better to `^4.9.0` since that is the required version.

2023-07-03 16:07 UTC, vivi90 commented on package.json
> +    "typescript": "^5.1.6"
Upgrade to TypeScript 5 is not neccessary and may break some type definitions.
Please use `^4.9.0`.

2023-07-17 18:33 UTC, rumpl commented
> But better to `^4.9.0` since that is the required version.

Required for what?

>  TypeScript 5 may break some type definitions.

Can you be more specific please?

2023-11-23 20:06 UTC, znarf commented
I think the tool should generally try to update its dependencies continuously to their latest version.

Here, if there is no test broken, we can assume that there is no breaking change and can move forward.

If we want to document a particular behavior and prevent against breaking changes, we should ideally have that covered with a test.

2024-01-11 10:35 UTC, rumpl approved these changes

2024-01-11 10:36 UTC, merged